# Ex5A NumPy Fundamentals
## Does what it says on the tin.
### High performance mathematical operations suited for data science

In [11]:
import numpy as np

## Array Basics

In [12]:
fruits = ["apple", "banana", "cherry", "data"]

In [13]:
arr_1 = fruits # defines arr_1
print(arr_1)

['apple', 'banana', 'cherry', 'data']


In [15]:
type(arr_1)
arr_1.dtype # This command didn't work for some reason, but it contains unicode string info
# arr_1 is defined as a list

AttributeError: 'list' object has no attribute 'dtype'

In [19]:
arr_2 = np.array([[10, 11, 12], # two dimensional array
                  [13, 14, 15]])

print(arr_2) # Prints array

[[10 11 12]
 [13 14 15]]


In [20]:
print(arr_2.T) # the Transpose statement

[[10 13]
 [11 14]
 [12 15]]


In [22]:
print(arr_2) # first print statement to test if values are changed...They are not

[[10 11 12]
 [13 14 15]]


In [23]:
arr_3 = np.array([[1, 3, 5], # Two dimensional array
                  [2, 4, 6]])

In [24]:
print(arr_3) # Typical array print statement

[[1 3 5]
 [2 4 6]]


In [26]:
arr_4 = np.array([arr_3[0, 2], arr_3[1, 1]]) # Array quatro

In [27]:
print(arr_4) # print

[5 4]


In [28]:
arr_5 = np.ones((2, 2, 2), dtype=int) # three dimensional array

In [29]:
print(arr_5) # You know what this does

[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]
