# Exercise 1.A NumPy: Manipulating Arrays

In [1]:
import numpy as np

## Looping Through Arrays

In [4]:
arrA = [
    [11, 12, 13],
    [14, 15, 16]
]

In [5]:
print(arrA)

[[11, 12, 13], [14, 15, 16]]


In [9]:
for x in arrA:
    print(x*2)

[11, 12, 13, 11, 12, 13]
[14, 15, 16, 14, 15, 16]


In [10]:
for y in x:
    print(y*2)

28
30
32


The first loop prints the array twice as informed by the (x*2). The second loop behaves differently by multiplying the y values in the array by two as opposed to printing it twice.

## Joining and Stacking Array

In [14]:
joined_array_1 = np.concatenate((arrA, arrA), axis=0)
print(joined_array_1)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [15]:
joined_array_2 = np.concatenate((arrA, arrA), axis=1)
print(joined_array_2)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


In [33]:
stacked_array_1 = np.concatenate((joined_array_1, joined_array_1), axis=0)
print(stacked_array_1)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [36]:
stacked_array_2 = np.concatenate((joined_array_1, joined_array_2), axis=0)
print(stacked_array_2)

#ValueError
# The array dimensions must match exactly in order to be stacked. the arrays do not match along dimension one.

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 6

In [38]:
another_2 = np.concatenate((joined_array_1, arrA), axis=1
                # Size mis-match along dimension zero.

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 2

In [48]:
VarH = np.hstack((arrA, arrA))
VarV = np.vstack((arrA, arrA))
VarD = np.dstack((arrA, arrA))

In [54]:
print(f" hstack \n {VarH}") # Horizontal stacking of arrays
print("\n ~~~~~~~~~~~")
print(f" vstack \n {VarV}") # Vertical stacking of arrays
print("\n ~~~~~~~~~~~")
print(f" dstack \n {VarD}") # 3d stacking of arrays


 hstack 
 [[11 12 13 11 12 13]
 [14 15 16 14 15 16]]

 ~~~~~~~~~~~
 vstack 
 [[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]

 ~~~~~~~~~~~
 dstack 
 [[[11 11]
  [12 12]
  [13 13]]

 [[14 14]
  [15 15]
  [16 16]]]


## Splitting Arrays

In [63]:
splitsky = np.split(joined_array_1, 2)
print(splitsky)

# splits the array into two even 2d arrays. Each array contains half the data.

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13],
       [14, 15, 16]])]


In [64]:
spliterino = np.array_split(joined_array_1, 3)
print(spliterino)
# Splits the array into three 2d arrays. each contains one third of the data. each has

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13]]), array([[14, 15, 16]])]


## Searching and Replacing Array Values

In [70]:
arrA = np.array(arrA) # Necessary conversion
result_1 = np.where(arrA % 2 == 0, arrA.astype(str), 'odd')
print(result_1)

[['odd' '12' 'odd']
 ['14' 'odd' '16']]


## Sorting and Filtering Arrays

In [72]:
# 2d array arrB
arrB = np.array([[7, 6],
                 [13, 5],
                 [7, 3]])

# Sorting arrB
arrB_sorted = np.sort(arrB)

# Print statement
print(arrB_sorted)

[[ 6  7]
 [ 5 13]
 [ 3  7]]


In [77]:
# Values less than 7
z = np.where(arrB < 7)
# Filter
arrC = arrB[z]
# Print
print(arrC)

[6 5 3]


In [78]:
# Values Greater than or equal to 7
d = np.where(arrB >= 7)
# Filter
arrD = arrB[d]
# Print
print(arrD)

[ 7 13  7]
