# Exercise 1.B NumPy Random

In [1]:
import numpy as np

## Generating Random Numbers

In [6]:
r_1 = np.random.randint(1, 20, size=2) # Two elements
print(r_1)

[11 13]


In [8]:
r_2 = np.random.randint(1, 20, size = (1, 2)) # 1 row two columns
print(r_2)

[[ 7 14]]


In [13]:
r_3 = np.random.uniform(0, 1, size = (2, 1))
print(r_3)

[[0.26404085]
 [0.25970874]]


In [19]:
r_4 = np.random.randint(20, 100, size = (4, 5))
print(r_4)

[[51 68 92 37 49]
 [99 67 45 41 49]
 [70 90 89 87 61]
 [36 32 85 28 71]]


In [21]:
r_5 = np.random.uniform(0, 1, size = (4, 5))
print(r_5)

[[0.29575501 0.80021002 0.55774366 0.45760984 0.29578988]
 [0.85307373 0.65047101 0.80747902 0.23165814 0.53423343]
 [0.77204374 0.70301844 0.50790411 0.87545558 0.65332988]
 [0.79700417 0.65213887 0.80236008 0.52750284 0.07383554]]


## Generating Random Choices

In [22]:
students = np.array([
    "Stan", "Kyle", "Cartman", "Kenny",
    "Butters", "Randy", "Wendy", "Token",
    "Jimmy", "Tweek"
])

In [25]:
call_on = np.random.choice(students)
print(call_on)

Kenny


In [28]:
breakout_groups = np.random.choice(students, size = (3, 4))
print(breakout_groups)

# This wouldn't be a very effective method of partitioning breakout groups because of duplicate assignments.
# Not possible to be in a breakout group with a clone of yourself...yet

[['Butters' 'Kyle' 'Stan' 'Stan']
 ['Wendy' 'Tweek' 'Token' 'Wendy']
 ['Wendy' 'Token' 'Tweek' 'Wendy']]


In [31]:
# Probabilities
prob = [0.10, 0.10, 0.30, 0.00, 0.10, 0.10, 0.10, 0.05, 0.10, 0.05]
# %30 chance of Cartman
# %0 chance of Kenny...you bastards!

In [42]:
call_on_weighted = np.random.choice(students, size=5, replace=False, p=prob)
print(call_on_weighted)

['Jimmy' 'Cartman' 'Butters' 'Wendy' 'Kyle']


## Generating a Normal Distribution

In [47]:
bell_curve = np.random.normal(loc=10, scale=5, size=(4, 5))
print(bell_curve)

[[ 6.7961038   6.8344025   4.99423336  2.30326668  7.37880075]
 [ 8.05849723 10.31842122 13.34379604 12.81595524  8.06997711]
 [ 5.32702225  8.83962385  9.82266349 22.32572434  5.45900965]
 [11.34816272 11.3489246  13.57771122  2.72585335  5.56501735]]
