# Exercise 1.C Performing Operations on Arrays

In [1]:
import numpy as np

## Sample Arrays

In [2]:
r_1 = np.random.randint(1, 20, size=2) # Two elements
print(r_1)

[ 6 14]


In [4]:
r_2 = np.random.randint(1, 20, size = (1, 2)) # 1 row two columns
print(r_2)

[[7 1]]


In [5]:
r_3 = np.random.uniform(0, 1, size = (2, 1))
print(r_3)

[[0.89753443]
 [0.02800319]]


In [6]:
r_4 = np.random.randint(20, 100, size = (4, 5))
print(r_4)

[[91 27 21 96 20]
 [37 45 52 54 88]
 [22 46 39 72 23]
 [67 22 91 40 58]]


In [7]:
r_5 = np.random.uniform(0, 1, size = (4, 5))
print(r_5)

[[7.65290680e-01 4.58614035e-01 4.82237009e-01 5.87455751e-01
  2.66953301e-01]
 [1.50151286e-01 7.09795633e-01 1.63058611e-04 5.88022202e-01
  5.74880553e-01]
 [3.39354813e-01 4.84389170e-01 3.03994866e-01 4.05561711e-01
  1.25741934e-01]
 [9.56109988e-01 5.56347893e-01 2.66995603e-01 6.76010565e-01
  5.20843001e-02]]


## Permutations

In [19]:
# Current value of r_4
print(r_4)
# Shuffled
np.random.shuffle(r_4)
print(f" Shuffled: \n {r_4}")

[[67 22 91 40 58]
 [91 27 21 96 20]
 [22 46 39 72 23]
 [37 45 52 54 88]]
 Shuffled: 
 [[67 22 91 40 58]
 [22 46 39 72 23]
 [37 45 52 54 88]
 [91 27 21 96 20]]


The order of the rows are shuffled while the values inside remain the same.

In [27]:
# New shuffs
new_shuffle = np.random.permutation(r_4)
original = r_4.copy()
# Print Statements
print(f"NEW SHUFFLE \n {new_shuffle}")
print(f"ORIGINAL \n {original}")


NEW SHUFFLE 
 [[37 45 52 54 88]
 [67 22 91 40 58]
 [22 46 39 72 23]
 [91 27 21 96 20]]
ORIGINAL 
 [[91 27 21 96 20]
 [67 22 91 40 58]
 [22 46 39 72 23]
 [37 45 52 54 88]]


Permutation is useful when you want to keep the original array intact. Shuffling your array will shuffle the output as well as the original array.

## Mathematical Operations

In [33]:
# r_1 and r_2
print(np.shape(r_1))
print(np.shape(r_2))
# Addition
print(np.shape(np.add(r_1, r_2)))

(2,)
(1, 2)
(1, 2)


In [36]:
# r_1 and r_3
print(np.shape(r_1))
print(np.shape(r_3))
print(np.shape(np.add(r_1, r_3)))

(2,)
(2, 1)
(2, 2)


In [54]:
# Reshape
new_r_4 = r_4.reshape(r_2)
# Starting Values
print(f"r_2: {r_2}")
print(f"Shape of r_2: {r_2.shape}")

print(f"r_4: {r_4}")
print(f"Shape of r_4: {r_4.shape}")

# Addition
result = np.add(r_2, new_r_4)

# Results
print(f"\n Result of r_2 + r_4: {result}")


######## ERROR ERROR ERROR I've tried to reshape a few different ways...#######

TypeError: only integer scalar arrays can be converted to a scalar index

In [42]:
# r_1 and r_4
# print(np.shape(np.add(r_1, r_4))) # Value Error
# r_2 and r_4
# print(np.shape(np.add(r_1, r_4))) # Value Error

ValueError: operands could not be broadcast together with shapes (2,) (4,5) 

In [56]:
# r_4 PlUS array [1]
PLUS = np.add(r_4, np.array([1]))

print(f"\n result of r_4 + [1]: {PLUS}")
print(f"\n Shape of PLUS: {PLUS.shape}")


 result of r_4 + [1]: [[92 28 22 97 21 68 23 92 41 59 23 47 40 73 24 38 46 53 55 89]]

 Shape of PLUS: (1, 20)


In [57]:
# r_4 PlUS array [[1]]
PLUS2 = np.add(r_4, np.array([[1]]))

print(f"\n result of r_4 + [[1]]: {PLUS2}")
print(f"\n Shape of PLUS2: {PLUS2.shape}")


 result of r_4 + [[1]]: [[92 28 22 97 21 68 23 92 41 59 23 47 40 73 24 38 46 53 55 89]]

 Shape of PLUS2: (1, 20)


In [62]:
# r_4 PLUS array [1, 1, 1, 1, 1,]
sliced = r_4.flatten()[:5] # had to take slice to match shapes
Arrayz = np.array([1, 1, 1, 1, 1,])

PLUS3 = np.add(sliced, Arrayz)
print(f"\n result: {PLUS3}")
print(f"\n Shape of PLUS3: {PLUS3.shape}")


 result: [92 28 22 97 21]

 Shape of PLUS3: (5,)


In [66]:
# r_4 PLUS array ([[1], [1]])
Arrayz = np.array([[1], [1]])

PLUS4 = np.add(r_4, Arrayz)
print(f"\n result: {PLUS3}")
print(f"\n Shape of PLUS4: {PLUS4.shape}")

# Didn't produce an error message...was it supposed to?


 result: [[92 28 22 97 21 68 23 92 41 59 23 47 40 73 24 38 46 53 55 89]
 [92 28 22 97 21 68 23 92 41 59 23 47 40 73 24 38 46 53 55 89]]

 Shape of PLUS4: (2, 20)


Broadcasting stretches a smaller array so that it is compatible for operation with larger arrays.

When using the add function, you are adding the two (or more) arrays which leaves you with one combined array.

## Rounding

In [74]:
# displaying r_3 values
print(r_3)
print("\n ~~~~~~~~~")
# ~~~~~~~~~

print(f" TRUNC: {np.trunc(r_3)}")
print(f" FIX: {np.fix(r_3)}")
print(f" FLOOR: {np.floor(r_3)}")
print(f" CEIL: {np.ceil(r_3)}")
print(f" ROUND(2): {np.round(r_3, 2)}")

[[0.89753443]
 [0.02800319]]

 ~~~~~~~~~
 TRUNC: [[0.]
 [0.]]
 FIX: [[0.]
 [0.]]
 FLOOR: [[0.]
 [0.]]
 CEIL: [[1.]
 [1.]]
 ROUND(2): [[0.9 ]
 [0.03]]


## Cumulative Operations

In [85]:
# Display r_4 values
print(r_4)
# SUM
print(f" Total sum of r_4: {np.sum(r_4)}")

print(f" Sum along 0 axis: {np.sum((r_4), axis=0)}")

print(f" Sum along 1 axis: {np.sum((r_4), axis=1)}")

print(f" cummulative sum: {np.cumsum((r_4))}")

print(f" Cummulative sum axis 0: {np.sum((r_4), axis=0)}")

[[91 27 21 96 20 67 22 91 40 58 22 46 39 72 23 37 45 52 54 88]]
 Total sum of r_4: 1011
 Sum along 0 axis: [91 27 21 96 20 67 22 91 40 58 22 46 39 72 23 37 45 52 54 88]
 Sum along 1 axis: [1011]
 cummulative sum: [  91  118  139  235  255  322  344  435  475  533  555  601  640  712
  735  772  817  869  923 1011]
 Cummulative sum axis 0: [91 27 21 96 20 67 22 91 40 58 22 46 39 72 23 37 45 52 54 88]


## Grocery Problem

In [86]:
# Define arrays
bag1 = [2, 3, 4, 0]
bag2 = [4, 0, 1, 2]

# Print 
print("bag1:", bag1)
print("bag2:", bag2)

bag1: [2, 3, 4, 0]
bag2: [4, 0, 1, 2]


In [90]:
# Total number of items in each bag
print(f"The first bag contains {np.sum(bag1)} items")
print(f"The second bag contains {np.sum(bag2)} items")

The first bag contains 9 items
The second bag contains 7 items


In [94]:
# Totals of each cat
total_vegetables = bag1[0]+bag2[0]
total_snacks = bag1[1]+bag2[1]
total_bev = bag1[2]+bag2[2]
total_fruit = bag1[3]+bag2[3]
# print sentence
print(f" There are {total_vegetables} vegetables, {total_fruit} fruits, {total_snacks} snacks and {total_bev} beverages.")

 There are 6 vegetables, 2 fruits, 3 snacks and 5 beverages.


## Teamwork

In [112]:
# Doors Knocked On
ali_doors = [5, 4, 6, 4, 2]
ben_doors = [0, 5, 5, 3, 4] # missed mondee
carla_doors = [3, 6, 0, 3, 4] # missed wednesdee

# SUM OF KNOCKS
all_knocks = np.sum(ali_doors + ben_doors + carla_doors)
print(f"ALL KNOCKS = {all_knocks}")

# Totals by knockers
ali_total = sum(ali_doors)
ben_total = sum(ben_doors)
carla_total = sum(carla_doors)

# Totals by group
group_total = ali_total + ben_total + carla_total

# Print Statements
print(f"Ali knocked on {ali_total} doors.")
print(f"Ben knocked on {ben_total} doors.")
print(f"Carla knocked on {carla_total} doors.")

# daily totals
daily_totals = []
for i in range(5):
    total = ali_doors[i] + ben_doors[i] + carla_doors[i]
    daily_totals.append(total)

# Rolling totals
rolling_totals = []
running_sum = 0

for day in daily_totals:
    running_sum += day
    rolling_totals.append(running_sum)

# Estimated votes
estimated_votes = [total * 0.5 for total in rolling_totals]

print("Rolling estimated votes by day:", estimated_votes)


ALL KNOCKS = 54
Ali knocked on 21 doors.
Ben knocked on 17 doors.
Carla knocked on 16 doors.
Rolling estimated votes by day: [4.0, 11.5, 17.0, 22.0, 27.0]
